paths:
  raw_path: "data/raw/dataset.csv"
  interim_path: "data/interim/interim_data.csv"
  processed_path: "data/processed/processed_data.csv"

preprocessing:
  service_cols:
    - "PhoneService"
    - "MultipleLines"
    - "OnlineSecurity"
    - "OnlineBackup"
    - "DeviceProtection"
    - "TechSupport"
    - "StreamingTV"
    - "StreamingMovies"
  numerical_cols:
    - "SeniorCitizen"
    - "MonthlyCharges"
    - "TotalCharges"
    - "HasFamily"
    - "TotalService"
    - "TotalCharges_log"
  categorical_cols:
    - "gender"
    - "Partner"
    - "Dependents"
    - "PhoneService"
    - "MultipleLines"
    - "InternetService"
    - "OnlineSecurity"
    - "OnlineBackup"
    - "DeviceProtection"
    - "TechSupport"
    - "StreamingTV"
    - "StreamingMovies"
    - "Contract"
    - "PaperlessBilling"


train_settings:
  test_size: 0.2
  random_state: 42
  target_col: "Churn"


model:
  module: "sklearn.linear_model"
  model_name: "LogisticRegression"
  params:
    C: 0.1
    penalty: "l2"
    class_weight: "balanced"
    solver: "lbfgs"
    max_iter: 1000
    random_state: 42



metrics:
  - module: "sklearn.metrics"
    name: "classification_report"

  - module: "sklearn.metrics"
    name: "confusion_matrix"


  - module: "sklearn.metrics"
    name: "roc_curve"